# Средние центры и окружение: национальное продолжение

Исполненное продолжение 25 октября 2026. Независимые исходы: население, торговые запасы и площадь; история WB/Ozon анализируется отдельно. Ни одна таблица ниже не является причинным эффектом платформ. Полный русский научный текст — `research/ecommerce_cloud/REPORT_RU.md`.

In [1]:
from pathlib import Path
import json, subprocess, sys
import pandas as pd
from IPython.display import display
ROOT=Path.cwd()
HERE=ROOT/'research/ecommerce_cloud/extension'
assert (ROOT/'AGENTS.md').exists()
result=subprocess.run([sys.executable,str(HERE/'run_extension.py')],cwd=ROOT,capture_output=True,text=True)
print(result.stdout[-2500:])
if result.returncode: print(result.stderr[-5000:])
assert result.returncode==0
print('Python:',sys.version.split()[0])

я": 6,
        "тульская": 4,
        "карелия": 1,
        "ненецкий": 1,
        "владимирская": 1,
        "кабардино балкарская": 5,
        "воронежская": 6,
        "астраханская": 3,
        "волгоградская": 10,
        "башкортостан": 7,
        "марий эл": 2,
        "мордовия": 4,
        "самарская": 1,
        "саратовская": 9,
        "костромская": 1,
        "курская": 6,
        "томская": 1
      }
    }
  ],
  "failures": []
}
Recalculating review/independent_new_outcomes.py
{
  "scope": "raw values for every medium panel and independent derived arithmetic; does not verify unpublished composition or source statistical accuracy",
  "failures": [],
  "recent_population": {
    "n": 170,
    "regions": 34,
    "share_increase": 152,
    "share_decrease": 18,
    "median_share_change_pp": 0.3579004235484573,
    "raw_values_checked": 1020
  },
  "area": {
    "n": 326,
    "raw_values_checked": 1956,
    "source_units": [
      "Квадратный метр"
    ]
  },
  "sensitivity_checks": [
    {
      "sensitivity": "all_reported",
      "category": "Магазины",
      "n": 169,
      "verified": true
    },
    {
      "sensitivity": "all_reported",
      "category": "Специализированные непродовольственные магазины",
      "n": 157,
      "verified": true
    },
    {
      "sensitivity": "exclude_oryol_all",
      "category": "Магазины",
      "n": 161,
      "verified": true
    },
    {
      "sensitivity": "exclude_oryol_all",
      "category": "Специализированные непродовольственные магазины",
      "n": 148,
      "verified": true
    },
    {
      "sensitivity": "exclude_factor2_breaks",
      "category": "Магазины",
      "n": 160,
      "verified": true
    },
    {
      "sensitivity": "exclude_factor2_breaks",
      "category": "Специализированные непродовольственные магазины",
      "n": 139,
      "verified": true
    },
    {
      "sensitivity": "exclude_oryol_and_factor2",
      "category": "Магазины",
      "n": 158,
      "verified": true
    },
    {
      "sensitivity": "exclude_oryol_and_factor2",
      "category": "Специализированные непродовольственные магазины",
      "n": 136,
      "verified": true
    }
  ]
}
Recalculating review/independent_spatial_check.py
{"method": "Brute-force haversine distances to all 144149 point records; 16 centres selected evenly across sorted IDs, four radii where supported", "n": 63, "failures": 0}
New descriptive analyses and independent arithmetic checks completed. No causal effect estimated.

Python: 3.12.14

## Исходы после переписи
170 средних центров, 34 региона; 1 января 2023–2025. Окружение — остаток муниципального района. Полный состав 2023/2024 не подтверждён. Совпадение с городской таблицей проверяет две публикации одного процесса Росстата, а не независимые измерения.

In [2]:
p=json.loads((HERE/'outcomes/recent_population_summary.json').read_text())
display(pd.DataFrame(p['results']))
display(pd.DataFrame([json.loads((HERE/'outcomes/urban_remainders_summary.json').read_text())]))

                                               scope  ...  urban_exact_match_n
0                                     all_candidates  ...                  146
1                                         medium2002  ...                  117
2  medium2002_district_no_publisher_transformatio...  ...                  115

[3 rows x 15 columns]

   medium_named_urban_centres_n  ...              difference_from_lower_municipal_panel
0                           160  ...  Named own urban population from frozen officia...

[1 rows x 11 columns]

## Количество, площадь, центр и окружение
174 торговых центра — 13,67% из 1273, 35 из 81 региона. Площадь не приравнивается к обороту или мощности. Десятикратные разрывы не исправлены догадкой; исключения показаны как чувствительность.

In [3]:
display(pd.read_csv(HERE/'outcomes/centre_periphery_stock_types.csv'))
display(pd.read_csv(HERE/'outcomes/area_sensitivity.csv'))
display(pd.read_csv(HERE/'outcomes/selection_characteristics.csv'))

         stock_centre_periphery_type  centres_n
0  centre_decline__periphery_decline         37
1   centre_decline__periphery_growth         14
2   centre_decline__periphery_stable          4
3   centre_growth__periphery_decline         56
4    centre_growth__periphery_growth         24
5    centre_growth__periphery_stable          4
6   centre_stable__periphery_decline         19
7    centre_stable__periphery_growth          8
8    centre_stable__periphery_stable          8

                 sensitivity  ... max_share_change_pp
0               all_reported  ...           71.580190
1               all_reported  ...           87.099931
2          exclude_oryol_all  ...           47.211305
3          exclude_oryol_all  ...           87.099931
4     exclude_factor2_breaks  ...           19.084645
5     exclude_factor2_breaks  ...           19.972909
6  exclude_oryol_and_factor2  ...           19.084645
7  exclude_oryol_and_factor2  ...           19.972909

[8 rows x 12 columns]

    in_shop_panel  ...           q75
0           False  ...  22132.500000
1           False  ...  19961.500000
2           False  ...     81.000000
3           False  ...     74.000000
4           False  ...     -1.916107
5           False  ...      7.442660
6           False  ...      1.000000
7            True  ...  19409.000000
8            True  ...  18189.250000
9            True  ...     74.750000
10           True  ...     67.500000
11           True  ...     -0.395389
12           True  ...      5.976822
13           True  ...      1.000000

[14 rows x 7 columns]

## География и масштаб
Фиксированные круги перекрываются и не являются наблюдёнными ареалами. Порог в процентных пунктах зависит от размера доли, поэтому отдельно показаны знак и логарифмический относительный темп.

In [4]:
display(pd.read_csv(HERE/'demographic_size.csv'))
display(pd.read_csv(HERE/'spatial_sensitivity.csv'))

      size2002  ...  median_share_change_pp
0    5000–9999  ...                5.592191
1  10000–19999  ...                3.945868
2  20000–49999  ...                2.244377

[3 rows x 9 columns]

   radius_km  ...  common_circle_median_change_pp
0         10  ...                        0.883194
1         20  ...                        2.180279
2         40  ...                        1.092536
3         80  ...                        0.085978

[4 rows x 13 columns]

## Исторические свидетельства
Новое Ozon API расширяет историю назад до 2021 года и добавляет Ростов, но остаётся оконной выборкой. Постоянный кодовый профиль WB не равен постоянной полноте и открытиям.

In [5]:
display(pd.read_csv(HERE/'history/ozon_cms_summary.csv'))
display(pd.read_csv(HERE/'history/wb_historical_profile_summary.csv')) if (HERE/'history/wb_historical_profile_summary.csv').exists() else display(pd.read_csv(HERE/'history/wb_historical_profile.csv'))
display(pd.read_csv(HERE/'history/wb_historical_pairs.csv').head())

  observation_date  ...  national_complete
0       2022-06-16  ...              False
1       2021-07-04  ...              False
2       2022-03-11  ...              False
3       2022-06-16  ...              False
4       2023-03-13  ...              False

[5 rows x 16 columns]

  observation_date  ...  profile_positive_fitting_or_unknown
0       2022-09-29  ...                                22120
1       2022-11-18  ...                                22970
2       2023-01-01  ...                                23697
3       2023-05-30  ...                                25658
4       2023-07-06  ...                                25642
5       2023-08-15  ...                                25744
6       2024-03-11  ...                                34306

[7 rows x 6 columns]

        date0       date1  ...  stable_ids_dtype_changed  stable_ids_isWb_changed
0  2022-09-29  2022-11-18  ...                         0                        0
1  2022-09-29  2023-01-01  ...                         0                        0
2  2022-09-29  2023-05-30  ...                         0                        0
3  2022-09-29  2023-07-06  ...                         1                        1
4  2022-09-29  2023-08-15  ...                         1                        1

[5 rows x 15 columns]

## Независимая проверка
Пересчёт первичных значений, вычитания окружения и прямых расстояний проверяет арифметику. Границы, полнота архивов и контрфактуал этими проверками не доказываются.

In [6]:
for name in ['independent_csv_results.json','independent_new_outcomes_results.json','independent_spatial_results.json']:
 p=HERE/'review'/name
 if p.exists():
  x=json.loads(p.read_text()); x.pop('checks',None);print(name);display(x)
print('Причинный эффект: не идентифицирован.')

independent_csv_results.json
independent_new_outcomes_results.json
independent_spatial_results.json
Причинный эффект: не идентифицирован.

{'scope': 'Independent recomputation from saved CSV; not raw acquisition audit or causal identification',
 'demography': {'medium_n': 1273,
  'supported_n': 1195,
  'median_change_pct': -11.497936605496529,
  'median_share_change_pp': 4.063733791920058,
  'share_gain_ge1pp_n': 946,
  'share_loss_le_minus1pp_n': 108},
 'trade': [{'category': 'Магазины',
   'n': 174,
   'share_loss_ge1pp_n': 26,
   'share_gain_ge1pp_n': 84,
   'stock_decline_n': 55,
   'stock_growth_n': 84,
   'median_share_change_pp': 0.8814869341185165,
   'selected_regions_n': 35,
   'all_medium_regions_n': 81,
   'selected_median_population2002': 11105.0,
   'not_selected_median_population2002': 11204.0,
   'selected_region_counts': {'коми': 2,
    'адыгея': 1,
    'кабардино балкарская': 7,
    'калмыкия': 4,
    'северная осетия алания': 3,
    'чеченская': 3,
    'краснодарский': 6,
    'башкортостан': 9,
    'татарстан': 1,
    'пензенская': 14,
    'алтай': 2,
    'тыва': 2,
    'алтайский': 14,
    'иркутская': 5,
    'новосибирская': 11,
    'омская': 2,
    'саха якутия': 9,
    'хабаровский': 7,
    'камчатский': 1,
    'орловская': 10,
    'брянская': 7,
    'тульская': 4,
    'карелия': 1,
    'ненецкий': 1,
    'владимирская': 1,
    'воронежская': 6,
    'астраханская': 3,
    'волгоградская': 12,
    'марий эл': 2,
    'мордовия': 4,
    'самарская': 1,
    'саратовская': 11,
    'костромская': 1,
    'курская': 6,
    'томская': 1}},
  {'category': 'Специализированные непродовольственные магазины',
   'n': 161,
   'share_loss_ge1pp_n': 26,
   'share_gain_ge1pp_n': 26,
   'stock_decline_n': 43,
   'stock_growth_n': 55,
   'median_share_change_pp': 0.0,
   'selected_regions_n': 35,
   'all_medium_regions_n': 81,
   'selected_median_population2002': 11471.0,
   'not_selected_median_population2002': 11124.5,
   'selected_region_counts': {'коми': 2,
    'адыгея': 1,
    'калмыкия': 4,
    'северная осетия алания': 3,
    'чеченская': 3,
    'краснодарский': 6,
    'татарстан': 1,
    'пензенская': 11,
    'алтай': 2,
    'тыва': 2,
    'алтайский': 14,
    'иркутская': 5,
    'новосибирская': 11,
    'омская': 2,
    'саха якутия': 9,
    'хабаровский': 7,
    'камчатский': 1,
    'орловская': 9,
    'брянская': 6,
    'тульская': 4,
    'карелия': 1,
    'ненецкий': 1,
    'владимирская': 1,
    'кабардино балкарская': 5,
    'воронежская': 6,
    'астраханская': 3,
    'волгоградская': 10,
    'башкортостан': 7,
    'марий эл': 2,
    'мордовия': 4,
    'самарская': 1,
    'саратовская': 9,
    'костромская': 1,
    'курская': 6,
    'томская': 1}}],
 'failures': []}

{'scope': 'raw values for every medium panel and independent derived arithmetic; does not verify unpublished composition or source statistical accuracy',
 'failures': [],
 'recent_population': {'n': 170,
  'regions': 34,
  'share_increase': 152,
  'share_decrease': 18,
  'median_share_change_pp': 0.3579004235484573,
  'raw_values_checked': 1020},
 'area': {'n': 326,
  'raw_values_checked': 1956,
  'source_units': ['Квадратный метр']},
 'sensitivity_checks': [{'sensitivity': 'all_reported',
   'category': 'Магазины',
   'n': 169,
   'verified': True},
  {'sensitivity': 'all_reported',
   'category': 'Специализированные непродовольственные магазины',
   'n': 157,
   'verified': True},
  {'sensitivity': 'exclude_oryol_all',
   'category': 'Магазины',
   'n': 161,
   'verified': True},
  {'sensitivity': 'exclude_oryol_all',
   'category': 'Специализированные непродовольственные магазины',
   'n': 148,
   'verified': True},
  {'sensitivity': 'exclude_factor2_breaks',
   'category': 'Магазины',
   'n': 160,
   'verified': True},
  {'sensitivity': 'exclude_factor2_breaks',
   'category': 'Специализированные непродовольственные магазины',
   'n': 139,
   'verified': True},
  {'sensitivity': 'exclude_oryol_and_factor2',
   'category': 'Магазины',
   'n': 158,
   'verified': True},
  {'sensitivity': 'exclude_oryol_and_factor2',
   'category': 'Специализированные непродовольственные магазины',
   'n': 136,
   'verified': True}]}

{'method': 'Brute-force haversine distances to all 144149 point records; 16 centres selected evenly across sorted IDs, four radii where supported',
 'n': 63,
 'failures': 0}